// AUTO-GENERATED by tools/prepare_mnist_wide.py — do not edit.
localparam NUM_CLUSTERS            = 4;
localparam NUM_NEURONS_PER_CLUSTER = 128;
localparam TOTAL_NEURONS           = 512;
localparam GRID                    = 10;
localparam NUM_INPUT               = 100;
localparam AXON_BASE               = 0;
localparam NEURON_BASE             = 100;
localparam NUM_EXC                 = 28;
localparam TOTAL_EXC               = 112;
localparam N_IMAGES                = 1200;
localparam TIMESTEPS_PER_IMG       = 20;
localparam BASE_THRESHOLD          = 1500;
