// AUTO-GENERATED by tools/prepare_mnist_stdp.py — do not edit.
localparam NUM_NEURONS_PER_CLUSTER = 128;
localparam NEURON_ADDRESS_WIDTH    = 7;
localparam BANK_DEPTH              = 128;
localparam NUM_INPUT               = 100;
localparam GRID                    = 10;
localparam NUM_EXC                 = 28;
localparam EXC_START               = 100;
localparam EXC_END                 = 127;
localparam N_IMAGES                = 1200;
localparam TIMESTEPS_PER_IMG       = 20;
localparam BASE_THRESHOLD          = 1500;
