// AUTO-GENERATED by tools/prepare_mnist_wide.py — do not edit.
localparam NUM_CLUSTERS            = 2;
localparam NUM_NEURONS_PER_CLUSTER = 256;
localparam TOTAL_NEURONS           = 512;
localparam GRID                    = 14;
localparam NUM_INPUT               = 196;
localparam AXON_BASE               = 0;
localparam NEURON_BASE             = 196;
localparam NUM_EXC                 = 60;
localparam TOTAL_EXC               = 120;
localparam N_IMAGES                = 1200;
localparam TIMESTEPS_PER_IMG       = 15;
localparam BASE_THRESHOLD          = 1500;
