// =============================================================================
// Testbench: tb_mnist_inference
// MNIST digit classification on the SNN accelerator.
//
// Architecture
// ─────────────────────────────────────────────────────────────────────────────
//   NUM_NEURONS_PER_CLUSTER = 256
//   Neurons   0–9  : output layer (one node per digit class 0–9)
//   Neurons 10–209 : hidden layer (200 neurons)
//   Neurons 210–255: unused
//
// Input path
// ─────────────────────────────────────────────────────────────────────────────
//   prepare_mnist.py rate-encodes MNIST images through a fixed random
//   784→200 projection and writes sparse (top-K) spike patterns to hex files.
//   Each timestep's 256-bit pattern is applied on external_spike_input_bus.
//   Only bits [209:10] (hidden neuron range) are ever set.
//
// Learning / inference
// ─────────────────────────────────────────────────────────────────────────────
//   Connection table setup (both directions):
//     connection_table[output_o][hidden_h] = 2'b10
//       → hidden_h is PRE to output_o (LTP when output fires)
//     connection_table[hidden_h][output_o] = 2'b01
//       → hidden_h is PRE to output_o (forward weight distribution when hidden fires)
//   When a hidden neuron fires, the STDP controller distributes W[output_o][hidden_h]
//   to output neuron o via the weight distribution bus. The real LIF neuron in
//   gen_neurons[o].neuron_inst integrates these synaptic currents and fires when
//   its membrane potential exceeds threshold.
//   STDP updates weights online; no hardware backpropagation is used.
//
// Classification
// ─────────────────────────────────────────────────────────────────────────────
//   Phase 1 — Calibration (first N_CALIBRATE images):
//     For each digit class, sum the spike counts of each output neuron
//     across all calibration images of that class.
//     Assign: label_to_neuron[digit] = argmax output neuron.
//   Phase 2 — Test (remaining N_IMAGES − N_CALIBRATE images):
//     For each image find the most-active output neuron, map back to a
//     digit via label_to_neuron[], compare against the true label.
//
// Required files (generated by tools/prepare_mnist.py, then copied to ./
// by the Makefile before VVP runs):
//   mnist_spikes.hex   N_IMAGES×TIMESTEPS_PER_IMG lines, 64 hex chars each
//   mnist_labels.hex   N_IMAGES lines, 1 hex char each (0–9)
//   init_weights.hex   65536 lines, 2 hex chars each
//
// NOTE on LIF firing:
//   This testbench uses the REAL simple_LIF_Neuron_Model (RTL_ALL target in
//   Makefile). Whether output neurons fire depends on the LIF threshold
//   relative to accumulated synaptic weight. If total_output_spikes = 0 after
//   calibration, increase --init-weight in prepare_mnist.py (e.g. to 240).
//
// Tuning knobs at the top of this file:
//   N_IMAGES, N_CALIBRATE, TIMESTEPS_PER_IMG, STDP_WAIT_CYCLES
//   Or override from Makefile: make test_mnist MNIST_IMAGES=500 MNIST_TIMESTEPS=30
// =============================================================================

`timescale 1ns/1ps

module tb_mnist_inference;

    // =========================================================================
    // ── User-configurable simulation parameters ───────────────────────────────
    // =========================================================================
    // Change these to control the run without modifying anything else.
    parameter N_IMAGES          = 200;   // Total images (cal + test).  Must equal
                                          // --images value used in prepare_mnist.py.
    parameter N_CALIBRATE       = 100;   // Calibration images (must be < N_IMAGES).
    parameter TIMESTEPS_PER_IMG = 20;    // Must equal --timesteps in prepare_mnist.py.
    parameter CLK_PERIOD_NS     = 10;
    parameter MAX_SIM_CYCLES    = 60_000_000; // Watchdog. Raise if simulation is cut short.
    parameter STDP_WAIT_CYCLES  = 6000;       // Per-timestep drain limit.
                                               // Raise if STDP is slow for 256-neuron cluster.

    // =========================================================================
    // ── Cluster parameters (must match prepare_mnist.py constants) ────────────
    // =========================================================================
    parameter NUM_NEURONS_PER_CLUSTER    = 256;
    parameter NEURON_ADDRESS_WIDTH       = 8;
    parameter NUM_WEIGHT_BANKS           = 256;
    parameter WEIGHT_BANK_ADDRESS_WIDTH  = 8;
    parameter WEIGHT_BIT_WIDTH           = 8;
    parameter TRACE_VALUE_BIT_WIDTH      = 8;
    parameter DECAY_TIMER_BIT_WIDTH      = 12;
    parameter TRACE_SATURATION_THRESHOLD = 256;
    parameter DECAY_SHIFT_LOG2           = 3;
    parameter TRACE_INCREMENT_VALUE      = 32;
    parameter NUM_TRACE_UPDATE_MODULES   = 4;
    parameter SPIKE_QUEUE_DEPTH          = 256;
    parameter LTP_SHIFT_AMOUNT           = 2;
    parameter LTD_SHIFT_AMOUNT           = 2;
    parameter INCREASE_MODE              = 0;

    // Neuron layout — must match prepare_mnist.py
    parameter OUTPUT_START = 0;
    parameter OUTPUT_END   = 9;
    parameter HIDDEN_START = 10;
    parameter HIDDEN_END   = 209;
    parameter NUM_OUTPUT   = 10;
    parameter NUM_HIDDEN   = 200;

    // =========================================================================
    // ── DUT ports ─────────────────────────────────────────────────────────────
    // =========================================================================
    reg  clock;
    reg  reset;
    reg  global_cluster_enable;
    reg  decay_enable_pulse;
    reg  [NUM_NEURONS_PER_CLUSTER-1:0] external_spike_input_bus;
    wire [NUM_NEURONS_PER_CLUSTER-1:0] cluster_spike_output_bus;
    wire                               cluster_busy_flag;

    // =========================================================================
    // ── DUT ───────────────────────────────────────────────────────────────────
    // =========================================================================
    neuron_cluster #(
        .NUM_NEURONS_PER_CLUSTER    (NUM_NEURONS_PER_CLUSTER),
        .NEURON_ADDRESS_WIDTH       (NEURON_ADDRESS_WIDTH),
        .NUM_WEIGHT_BANKS           (NUM_WEIGHT_BANKS),
        .WEIGHT_BANK_ADDRESS_WIDTH  (WEIGHT_BANK_ADDRESS_WIDTH),
        .WEIGHT_BIT_WIDTH           (WEIGHT_BIT_WIDTH),
        .TRACE_VALUE_BIT_WIDTH      (TRACE_VALUE_BIT_WIDTH),
        .DECAY_TIMER_BIT_WIDTH      (DECAY_TIMER_BIT_WIDTH),
        .TRACE_SATURATION_THRESHOLD (TRACE_SATURATION_THRESHOLD),
        .DECAY_SHIFT_LOG2           (DECAY_SHIFT_LOG2),
        .TRACE_INCREMENT_VALUE      (TRACE_INCREMENT_VALUE),
        .NUM_TRACE_UPDATE_MODULES   (NUM_TRACE_UPDATE_MODULES),
        .SPIKE_QUEUE_DEPTH          (SPIKE_QUEUE_DEPTH),
        .LTP_SHIFT_AMOUNT           (LTP_SHIFT_AMOUNT),
        .LTD_SHIFT_AMOUNT           (LTD_SHIFT_AMOUNT),
        .INCREASE_MODE              (INCREASE_MODE)
    ) uut (
        .clock                    (clock),
        .reset                    (reset),
        .global_cluster_enable    (global_cluster_enable),
        .decay_enable_pulse       (decay_enable_pulse),
        .external_spike_input_bus (external_spike_input_bus),
        .cluster_spike_output_bus (cluster_spike_output_bus),
        .cluster_busy_flag        (cluster_busy_flag)
    );

    // =========================================================================
    // ── Clock ─────────────────────────────────────────────────────────────────
    // =========================================================================
    initial clock = 0;
    always #(CLK_PERIOD_NS/2) clock = ~clock;

    // =========================================================================
    // ── Watchdog ──────────────────────────────────────────────────────────────
    // =========================================================================
    initial begin
        #(CLK_PERIOD_NS * MAX_SIM_CYCLES);
        $display("[WATCHDOG] Exceeded %0d cycles. Increase MAX_SIM_CYCLES or reduce N_IMAGES.",
                 MAX_SIM_CYCLES);
        $finish;
    end

    // =========================================================================
    // ── Data memory ───────────────────────────────────────────────────────────
    // =========================================================================
    // Spike patterns: N_IMAGES × TIMESTEPS_PER_IMG entries of 256 bits each.
    reg [255:0] spike_patterns [0:N_IMAGES*TIMESTEPS_PER_IMG-1];
    // Labels: N_IMAGES entries of 4 bits (digit 0–9).
    reg [3:0]   image_labels   [0:N_IMAGES-1];
    // Flat weight scratch buffer for $readmemh: 256 banks × 256 addresses.
    reg [7:0]   flat_weights   [0:NUM_WEIGHT_BANKS*256-1];

    // =========================================================================
    // ── Statistics ────────────────────────────────────────────────────────────
    // =========================================================================
    // cal_flat[digit * NUM_OUTPUT + neuron] accumulates output spikes during
    // calibration. Avoids a 2D integer array (not reliably supported in all
    // iverilog versions).
    integer cal_flat        [0:NUM_OUTPUT*NUM_OUTPUT-1];
    integer label_to_neuron [0:NUM_OUTPUT-1]; // digit → output neuron
    integer output_spikes   [0:NUM_OUTPUT-1]; // per-image output spike counts
    integer per_digit_correct[0:NUM_OUTPUT-1];
    integer per_digit_total  [0:NUM_OUTPUT-1];
    integer n_correct;
    integer n_tested;
    integer total_output_spikes; // diagnostic: 0 means LIF threshold issue

    // =========================================================================
    // ── Loop and scratch variables ────────────────────────────────────────────
    // =========================================================================
    integer img_i, t_i, o_i, h_i, d_i;
    integer wait_cyc;
    integer max_val, max_neuron, predicted_digit;
    real    accuracy_pct;

    // =========================================================================
    // ── Tasks ─────────────────────────────────────────────────────────────────
    // =========================================================================

    // Drain STDP: wait until cluster_busy_flag clears or timeout expires.
    task drain_stdp;
        input integer timeout;
        begin
            wait_cyc = 0;
            while (cluster_busy_flag && wait_cyc < timeout) begin
                @(posedge clock);
                wait_cyc = wait_cyc + 1;
            end
            #1;
        end
    endtask

    // Advance the global decay timer by one tick.
    task send_decay_pulse;
        begin
            decay_enable_pulse = 1;
            @(posedge clock);
            decay_enable_pulse = 0;
            @(posedge clock); #1;
        end
    endtask

    // Brief inter-image pause: disable cluster for 10 cycles then re-enable.
    // This gives the LIF neurons time to stop firing before the next image.
    // Does NOT reset the weight memory or connection table.
    task inter_image_pause;
        begin
            global_cluster_enable = 0;
            repeat(10) @(posedge clock);
            global_cluster_enable = 1;
            repeat(3) @(posedge clock); #1;
        end
    endtask

    // =========================================================================
    // ── run_image task ────────────────────────────────────────────────────────
    // Presents one image for TIMESTEPS_PER_IMG timesteps.
    // Clears output_spikes[] on entry; accumulates output spike counts.
    // =========================================================================
    task run_image;
        input integer img_idx;
        begin
            // Clear per-image counters
            for (o_i = 0; o_i < NUM_OUTPUT; o_i = o_i + 1)
                output_spikes[o_i] = 0;

            for (t_i = 0; t_i < TIMESTEPS_PER_IMG; t_i = t_i + 1) begin
                // Apply this timestep's spike pattern
                external_spike_input_bus =
                    spike_patterns[img_idx * TIMESTEPS_PER_IMG + t_i];
                @(posedge clock);
                external_spike_input_bus = {NUM_NEURONS_PER_CLUSTER{1'b0}};

                // Drain STDP triggered by hidden-neuron spikes
                drain_stdp(STDP_WAIT_CYCLES);

                // Sample output spike bus during / after STDP drain
                for (o_i = OUTPUT_START; o_i <= OUTPUT_END; o_i = o_i + 1)
                    if (cluster_spike_output_bus[o_i])
                        output_spikes[o_i] = output_spikes[o_i] + 1;

                // One decay tick between timesteps
                send_decay_pulse();
            end

            // Final drain for any spikes generated in the last timestep
            drain_stdp(STDP_WAIT_CYCLES);

            // One final sample
            for (o_i = OUTPUT_START; o_i <= OUTPUT_END; o_i = o_i + 1)
                if (cluster_spike_output_bus[o_i])
                    output_spikes[o_i] = output_spikes[o_i] + 1;
        end
    endtask

    // =========================================================================
    // ── Main test body ────────────────────────────────────────────────────────
    // =========================================================================
    initial begin
        $display("============================================================");
        $display("  MNIST SNN Inference Testbench");
        $display("  N_IMAGES          = %0d  (cal: %0d  test: %0d)",
                 N_IMAGES, N_CALIBRATE, N_IMAGES - N_CALIBRATE);
        $display("  TIMESTEPS_PER_IMG = %0d", TIMESTEPS_PER_IMG);
        $display("  NUM_NEURONS       = %0d", NUM_NEURONS_PER_CLUSTER);
        $display("  Hidden: [%0d..%0d]  Output: [%0d..%0d]",
                 HIDDEN_START, HIDDEN_END, OUTPUT_START, OUTPUT_END);
        $display("  STDP_WAIT_CYCLES  = %0d", STDP_WAIT_CYCLES);
        $display("============================================================");

        // ── Load hex files ────────────────────────────────────────────────
        $display("Loading mnist_spikes.hex …");
        $readmemh("mnist_spikes.hex", spike_patterns);
        $display("Loading mnist_labels.hex …");
        $readmemh("mnist_labels.hex", image_labels);
        $display("Loading init_weights.hex …");
        $readmemh("init_weights.hex", flat_weights);

        // ── Hardware reset ────────────────────────────────────────────────
        reset                    = 1;
        global_cluster_enable    = 0;
        decay_enable_pulse       = 0;
        external_spike_input_bus = {NUM_NEURONS_PER_CLUSTER{1'b0}};
        repeat(8) @(posedge clock); #1;
        reset = 0;
        @(posedge clock); #1;

        // ── Program weight memory ─────────────────────────────────────────
        // Copies flat_weights[bank*256 + addr] → bank_memory[bank][addr].
        // UPDATE PATH: 'weight_memory_inst' / 'bank_memory' must match your
        //              banked_weight_memory instance and array names.
        $display("Programming weight memory (%0d entries) …",
                 NUM_WEIGHT_BANKS * 256);
        begin : weight_load
            integer bk, ad;
            for (bk = 0; bk < NUM_WEIGHT_BANKS; bk = bk + 1)
                for (ad = 0; ad < 256; ad = ad + 1)
                    uut.weight_memory_inst.bank_memory[bk][ad] =
                        flat_weights[bk * 256 + ad];       // UPDATE PATH
        end
        @(posedge clock); #1;

        // ── Configure connection matrix ───────────────────────────────────
        // Sets BOTH directions for each hidden→output pair:
        //   connection_table[output][hidden] = 2'b10  (LTP when output fires)
        //   connection_table[hidden][output] = 2'b01  (weight distribution when hidden fires)
        // UPDATE PATH: 'connection_matrix_inst' / 'connection_table' must match
        //              your cluster_connection_matrix instance and array names.
        $display("Configuring connection matrix (%0d connections) …",
                 NUM_HIDDEN * NUM_OUTPUT * 2);
        begin : conn_load
            integer out_n, hid_n;
            for (out_n = OUTPUT_START; out_n <= OUTPUT_END; out_n = out_n + 1) begin
                for (hid_n = HIDDEN_START; hid_n <= HIDDEN_END; hid_n = hid_n + 1) begin
                    uut.connection_matrix_inst.connection_table[out_n][hid_n] = 2'b10; // UPDATE PATH
                    uut.connection_matrix_inst.connection_table[hid_n][out_n] = 2'b01; // UPDATE PATH
                end
            end
        end
        @(posedge clock); #1;

        // ── Initialise statistics ─────────────────────────────────────────
        for (d_i = 0; d_i < NUM_OUTPUT * NUM_OUTPUT; d_i = d_i + 1)
            cal_flat[d_i] = 0;
        for (d_i = 0; d_i < NUM_OUTPUT; d_i = d_i + 1) begin
            per_digit_correct[d_i] = 0;
            per_digit_total[d_i]   = 0;
        end
        total_output_spikes = 0;

        global_cluster_enable = 1;
        @(posedge clock); @(posedge clock); #1;

        // ==================================================================
        // PHASE 1 — Calibration
        // ==================================================================
        $display("");
        $display("─── Phase 1: Calibration (%0d images) ───────────────────", N_CALIBRATE);

        for (img_i = 0; img_i < N_CALIBRATE; img_i = img_i + 1) begin

            run_image(img_i);

            // Accumulate into calibration table
            d_i = image_labels[img_i];
            for (o_i = 0; o_i < NUM_OUTPUT; o_i = o_i + 1) begin
                cal_flat[d_i * NUM_OUTPUT + o_i] =
                    cal_flat[d_i * NUM_OUTPUT + o_i] + output_spikes[o_i];
                total_output_spikes = total_output_spikes + output_spikes[o_i];
            end

            inter_image_pause();

            if ((img_i + 1) % 20 == 0)
                $display("  [cal] %3d / %0d   output spikes accumulated: %0d",
                         img_i + 1, N_CALIBRATE, total_output_spikes);
        end

        $display("  Calibration complete. Total output spikes: %0d", total_output_spikes);

        // ── Diagnostic warning ────────────────────────────────────────────
        if (total_output_spikes == 0) begin
            $display("");
            $display("  WARNING ─── No output neurons fired during calibration.");
            $display("  The label mapping will be random; accuracy will be ~10%%.");
            $display("  Possible fixes:");
            $display("    1. Increase --init-weight in prepare_mnist.py (try 230–255).");
            $display("    2. Increase --timesteps (more synaptic inputs per image).");
            $display("    3. Check LIF neuron threshold in your Simple_LIF_Neuron_Model.");
            $display("");
        end

        // ── Build label → output-neuron mapping ───────────────────────────
        $display("");
        $display("─── Label mapping (argmax over calibration spikes) ──────────");
        for (d_i = 0; d_i < NUM_OUTPUT; d_i = d_i + 1) begin
            max_val    = -1;
            max_neuron = 0;
            for (o_i = 0; o_i < NUM_OUTPUT; o_i = o_i + 1) begin
                if (cal_flat[d_i * NUM_OUTPUT + o_i] > max_val) begin
                    max_val    = cal_flat[d_i * NUM_OUTPUT + o_i];
                    max_neuron = o_i;
                end
            end
            label_to_neuron[d_i] = max_neuron;
            $display("  digit %0d  →  output neuron %0d   (calib spikes: %0d)",
                     d_i, max_neuron, max_val);
        end

        // ==================================================================
        // PHASE 2 — Test
        // ==================================================================
        $display("");
        $display("─── Phase 2: Test (%0d images) ──────────────────────────────",
                 N_IMAGES - N_CALIBRATE);
        n_correct = 0;
        n_tested  = 0;

        for (img_i = N_CALIBRATE; img_i < N_IMAGES; img_i = img_i + 1) begin

            run_image(img_i);

            // Find most-active output neuron for this image
            max_val    = -1;
            max_neuron = -1;
            for (o_i = 0; o_i < NUM_OUTPUT; o_i = o_i + 1) begin
                if (output_spikes[o_i] > max_val) begin
                    max_val    = output_spikes[o_i];
                    max_neuron = o_i;
                end
            end

            // Map neuron → predicted digit
            predicted_digit = -1;
            if (max_val > 0) begin
                for (d_i = 0; d_i < NUM_OUTPUT; d_i = d_i + 1)
                    if (label_to_neuron[d_i] == max_neuron)
                        predicted_digit = d_i;
                // If multiple digits map to the same neuron, last wins —
                // sufficient for a coarse accuracy estimate.
            end

            // Tally
            d_i = image_labels[img_i]; // true label
            per_digit_total[d_i] = per_digit_total[d_i] + 1;
            if (predicted_digit == d_i) begin
                n_correct = n_correct + 1;
                per_digit_correct[d_i] = per_digit_correct[d_i] + 1;
            end
            n_tested = n_tested + 1;

            inter_image_pause();

            // Rolling accuracy every 10 test images
            if (n_tested % 10 == 0) begin
                accuracy_pct = (n_tested > 0) ?
                    (100.0 * n_correct / n_tested) : 0.0;
                $display("  [test] %3d / %0d   correct: %0d   accuracy: %0.1f%%",
                         n_tested, N_IMAGES - N_CALIBRATE,
                         n_correct, accuracy_pct);
            end
        end

        // ==================================================================
        // Final summary
        // ==================================================================
        accuracy_pct = (n_tested > 0) ?
            (100.0 * n_correct / n_tested) : 0.0;

        $display("");
        $display("============================================================");
        $display("  MNIST SNN INFERENCE — FINAL RESULTS");
        $display("  Calibration images : %0d", N_CALIBRATE);
        $display("  Test images        : %0d", n_tested);
        $display("  Correct            : %0d / %0d", n_correct, n_tested);
        $display("  Overall accuracy   : %0.2f%%", accuracy_pct);
        $display("  (Random-chance baseline = 10%%)");
        $display("");
        $display("  Per-digit breakdown:");
        for (d_i = 0; d_i < NUM_OUTPUT; d_i = d_i + 1) begin
            if (per_digit_total[d_i] > 0) begin
                accuracy_pct = 100.0 * per_digit_correct[d_i] / per_digit_total[d_i];
                $display("    digit %0d : %3d / %3d  (%0.1f%%)  → neuron %0d",
                         d_i,
                         per_digit_correct[d_i],
                         per_digit_total[d_i],
                         accuracy_pct,
                         label_to_neuron[d_i]);
            end
        end
        $display("");
        if (total_output_spikes == 0)
            $display("  NOTE: No output spikes observed. See calibration WARNING above.");
        $display("============================================================");
        $finish;
    end

endmodule
