// AUTO-GENERATED by tools/prepare_mnist_layered.py — do not edit.
localparam NUM_CLUSTERS            = 5;
localparam NUM_NEURONS_PER_CLUSTER = 64;
localparam TOTAL_NEURONS           = 320;
localparam GRID                    = 10;

localparam AXON_BASE               = 0;
localparam NUM_AXONS               = 32;
localparam NEURON_BASE             = 32;
localparam NUM_LOCAL_NEURONS       = 32;

localparam L1_CLUSTERS             = 4;
localparam L1_AXONS                = 25;
localparam L1_NEURONS              = 8;
localparam L2_CLUSTER              = 4;
localparam L2_AXONS                = 32;
localparam L2_NEURONS              = 32;

localparam N_IMAGES                = 1200;
localparam TIMESTEPS_PER_IMG       = 20;
localparam BASE_THRESHOLD          = 400;
